import React, { useEffect, useRef, useState } from 'react';
import { Link, RouteComponentProps } from 'react-router-dom';
import login from '@/api/auth/login';
import LoginFormContainer from '@/components/auth/LoginFormContainer';
import { useStoreState } from 'easy-peasy';
import { Formik, FormikHelpers } from 'formik';
import { object, string } from 'yup';
import Field from '@/components/elements/Field';
import tw from 'twin.macro';
import Button from '@/components/elements/Button';
import CaptchaWidget, { CaptchaWidgetHandle } from '@/components/elements/CaptchaWidget';
import useFlash from '@/plugins/useFlash';

interface Values {
    username: string;
    password: string;
}

const LoginContainer = ({ history }: RouteComponentProps) => {
    const ref = useRef<CaptchaWidgetHandle>(null);
    const [token, setToken] = useState('');
    const tokenRef = useRef('');

    const { clearFlashes, clearAndAddHttpError, addFlash } = useFlash();
    const { enabled: recaptchaEnabled, siteKey, provider } = useStoreState((state) => state.settings.data!.recaptcha);

    useEffect(() => {
        clearFlashes();
    }, []);

    const onSubmit = (values: Values, { setSubmitting }: FormikHelpers<Values>) => {
        console.log('VerifyReCaptcha: onSubmit triggered', { provider, recaptchaEnabled, hasToken: !!tokenRef.current });
        clearFlashes();

        // Trigger invisible captcha execution for Google before sending the request.
        if (recaptchaEnabled && provider === 'google' && !tokenRef.current) {
            console.log('VerifyReCaptcha: Triggering Google execute()');
            setSubmitting(false);
            ref.current?.execute().catch((error) => {
                console.error('VerifyReCaptcha: Google execute() failed', error);

                setSubmitting(false);
                clearAndAddHttpError({ error });
            });

            return;
        }

        console.log('VerifyReCaptcha: Calling login API');

        // Visible providers require a token already generated by their widget.
        if (recaptchaEnabled && provider !== 'google' && !tokenRef.current) {
            setSubmitting(false);
            addFlash({ type: 'error', title: 'Error', message: 'Please complete the CAPTCHA challenge.' });
            return;
        }

        login({ ...values, recaptchaData: tokenRef.current })
            .then((response) => {
                if (response.complete) {
                    // @ts-expect-error this is valid
                    window.location = response.intended || '/';
                    return;
                }

                history.replace('/auth/login/checkpoint', { token: response.confirmationToken });
            })
            .catch((error) => {
                console.error(error);

                tokenRef.current = '';
                setToken('');
                ref.current?.reset();

                setSubmitting(false);
                clearAndAddHttpError({ error });
            });
    };

    return (
        <Formik
            onSubmit={onSubmit}
            initialValues={{ username: '', password: '' }}
            validationSchema={object().shape({
                username: string().required('A username or email must be provided.'),
                password: string().required('Please enter your account password.'),
            })}
        >
            {({ isSubmitting, setSubmitting, submitForm }) => (
                <LoginFormContainer title={'Login to Continue'} css={tw`w-full flex`}>
                    <Field light type={'text'} label={'Username or Email'} name={'username'} disabled={isSubmitting} />
                    <div css={tw`mt-6`}>
                        <Field light type={'password'} label={'Password'} name={'password'} disabled={isSubmitting} />
                    </div>
                    <div css={tw`mt-6`}>
                        <Button type={'submit'} size={'xlarge'} isLoading={isSubmitting} disabled={isSubmitting}>
                            Login
                        </Button>
                    </div>
                    {recaptchaEnabled && (
                        <div css={tw`mt-4`}>
                            <CaptchaWidget
                                ref={ref}
                                provider={provider}
                                siteKey={siteKey || '_invalid_key'}
                                onVerify={(response) => {
                                    console.log('VerifyReCaptcha: onVerify called', { provider });
                                    tokenRef.current = response;
                                    setToken(response);
                                    if (provider === 'google') {
                                        console.log('VerifyReCaptcha: Triggering submitForm() for Google');
                                        submitForm();
                                    }
                                }}
                                onExpire={() => {
                                    console.log('VerifyReCaptcha: onExpire called');
                                    setSubmitting(false);
                                    tokenRef.current = '';
                                    setToken('');
                                }}
                            />
                        </div>
                    )}
                    <div css={tw`mt-6 text-center`}>
                        <Link
                            to={'/auth/password'}
                            css={tw`text-xs text-neutral-500 tracking-wide no-underline uppercase hover:text-neutral-600`}
                        >
                            Forgot password?
                        </Link>
                    </div>
                </LoginFormContainer>
            )}
        </Formik>
    );
};

export default LoginContainer;
